### ISSUE TITLE
Improve Journey interaction model

### ISSUE THREAD

**Issue by Rezonation** [rasmussaks/aken-ajalukku#41]
Perhaps requires improvements on Journey screen. Currently the "on journey" state is not communicated well enough. Should we force people to watch each video to progress? How do we display progress?

**Comment by underspikey** [comment]
Estimate: 10h

**Comment by underspikey** [comment]
Is this done? @Rezonation

**Comment by Rezonation** [comment]
Because I improved the bottom button to better reflect the state of the map and because @rasmussaks make the descision to make the Journey go on to the next PoI after the video has been opened, i think the issue, as it was presented, has no met some sort of a conclusion.
